var lay_id = layer_get_id("Backgrounds_1")
var back_id = layer_background_get_id(lay_id)
var lay_id2 = layer_get_id("Backgrounds_2")
var back_id2 = layer_background_get_id(lay_id2)
var lay_id3 = layer_get_id("Backgrounds_3")
var back_id3 = layer_background_get_id(lay_id3)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1226)
    layer_background_sprite(back_id, 1225)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1223)
    layer_background_sprite(back_id, 1224)
if (global.panic == 1 && layer_background_get_sprite(back_id3) == 1228)
    layer_background_sprite(back_id3, 1229)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1192)
    layer_background_sprite(back_id, 1193)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1195)
    layer_background_sprite(back_id, 1196)
if (global.panic == 1 && layer_background_get_sprite(back_id2) == 1197)
    layer_background_sprite(back_id2, 1198)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1262)
    layer_background_sprite(back_id, 1263)
if (global.panic == 1 && layer_background_get_sprite(back_id2) == 1260)
    layer_background_sprite(back_id2, 1261)
if (global.panic == 1 && layer_background_get_sprite(back_id3) == 1258)
    layer_background_sprite(back_id3, 1259)
